### ISSUE TITLE
More sources of inspiration

### ISSUE THREAD

**Issue by suhr** [chris-zen/hero-studio#24]
- [Helio Workstation](https://helio.fm/). A very neat app which is also open source
- [Sunvox](http://www.warmplace.ru/soft/sunvox/). This is a tracker, but a rather unique one.

**Comment by chris-zen** [comment]
@suhr thank you very much for the links. I already knew Sunvox, although I didn't explore it too much. But I was surprised by Helio Workstation, because it seems to have very similar goals to this project in terms of simplifying the DAW workflow. I will definitively take it as an inspiration.
I just updated the wiki to include them ;-)
https://github.com/chris-zen/hero-studio/wiki/state-of-the-art
